---
name: bosh-nginx
director_uuid: fb70f16a-4d6f-41f8-bc2e-0181a03dff18

releases:
- name: nginx
  version: latest

networks:
- name: default
  type: manual
  subnets:
  - range: 10.0.0.0/24
    gateway: 10.0.0.1
    static: [10.0.0.4]
    cloud_properties:
      subnet: subnet-66f7063e
      security_groups: [ph-bosh]
- name: public
  type: vip
  cloud_properties: {}

resource_pools:
- name: default
  network: default
  stemcell:
    name: bosh-aws-xen-ubuntu-trusty-go_agent
    version: latest
  cloud_properties:
    instance_type: m3.medium 
    availability_zone: eu-west-1a

compilation:
  workers: 1
  network: default
  cloud_properties: 
    instance_type: m3.medium 
    availability_zone: eu-west-1a

update:
  canaries: 1
  canary_watch_time: 60000
  update_watch_time: 60000
  max_in_flight: 2

jobs:
- name: nginx
  templates:
  - name: nginx
  instances: 1
  resource_pool: default
  networks:
  - name: default
    static_ips: [10.0.0.4]
    default: [gateway, dns]
  - name: public
    static_ips: [52.51.163.20]
  properties: {}

