---
name: bosh-nginx
director_uuid: fb70f16a-4d6f-41f8-bc2e-0181a03dff18

releases:
- name: nginx
  version: latest

networks:
- name: default
  type: manual
  subnets:
  - range: 10.244.8.0/24
    gateway: 10.244.8.1
    static: [10.244.8.5]
- name: public
  type: vip
  cloud_properties: {}

resource_pools:
- name: default
  network: default
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
  cloud_properties: {}

compilation:
  workers: 1
  network: default
  cloud_properties:
    instance_type: {}

update:
  canaries: 1
  canary_watch_time: 60000
  update_watch_time: 60000
  max_in_flight: 2

jobs:
- name: nginx
  templates:
  - name: nginx
  instances: 1
  resource_pool: default
  networks:
  - name: default
    static_ips: [10.244.8.5]
    default: [gateway, dns]
  properties: {}
